### PR TITLE
Added separate Initialization

### PR DESCRIPTION
**Pull request by JeanRemiDelteil**
Allow asynchronous loading beside JQuery

make a call to nhpup.initialize() on JQuery ready event

### CODE REVIEW

**Comment by nhoening** [comment]
Hi, this looks useful, thanks. I'll need some minutes off work to test it a bit before merging. Hopefully won't be too long.

**Comment by JeanRemiDelteil** [comment]
Thanks,
Here is the context of this modification:
https://plus.google.com/107715730987411040284/posts/ipNoQt1Bn6j

I wanted to load the 2 lib at the same time to improve loading time and the edit was there to ensure it works in all cases.

The default behavior will stay the same, so existing code will not need to be changed.

**Comment by nhoening** [comment]
Looks good to me, thanks again. Btw, is this popup script used by several people within Awesome Table world or just this one guy?

**Comment by JeanRemiDelteil** [comment]
It was the first person to bring it on the community, I'm not aware of
other uses.
But if people like the example some will probably use it too.

I like the functionality, but it uses jQuery so it takes some time to load.
I personally prefer pure JavaScript.

Jean-Rémi Delteil,
Awesome Table team

**Pull request merged**
